import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import * as XLSX from 'xlsx'
import { formatCurrency, getMonthName } from './utils'
import type { EmployeeWithPayroll } from '@/types/database'

export interface ReportData {
  month: number
  year: number
  employees: EmployeeWithPayroll[]
  totalGrossSalary: number
  totalDeductions: number
  totalAdditions: number
  totalNetSalary: number
  generatedBy: string
}

/**
 * Generate a comprehensive Excel report with full-width formatting
 */
export function generateExcelReport(data: ReportData): Blob {
  const { month, year, employees, totalGrossSalary, totalDeductions, totalAdditions, totalNetSalary, generatedBy } = data

  // Create workbook
  const wb = XLSX.utils.book_new()

  // Prepare header rows
  const headerRows = [
    ['PAYROLL REPORT'],
    [`${getMonthName(month)} ${year}`],
    [],
    ['Generated On:', new Date().toLocaleString()],
    ['Generated By:', generatedBy],
    [],
    ['Summary'],
    ['Total Employees:', employees.length],
    ['Total Gross Salary:', formatCurrency(totalGrossSalary)],
    ['Total Deductions:', formatCurrency(totalDeductions)],
    ['Total Additions:', formatCurrency(totalAdditions)],
    ['Total Net Salary:', formatCurrency(totalNetSalary)],
    [],
  ]

  // Prepare table headers - only actual fields from database
  const tableHeaders = [
    'Employee ID',
    'Employee Name',
    'Designation',
    'Department',
    'Employment Status',
    'Joining Date',
    'Payment Mode',
    'PF Applicable',
    'ESI Applicable',
    'Current Salary',
    'Deduction Type',
    'Deduction Amount',
    'Addition Type',
    'Addition Amount',
    'Incentive Type',
    'Incentive Amount',
    'PF Amount',
    'ESI Amount',
    'Net Pay',
    'HR Remark',
    'Salary Processing Required',
    'Payment Status',
    'Remarks',
    'Bank Name',
    'Account Number',
    'IFSC Code',
  ]

  // Prepare table data - only actual fields from database
  const tableData = employees.map((emp) => {
    const payroll = emp.payroll as any || {}
    return [
      emp.employee_id,
      emp.employee_name,
      emp.designation || '-',
      emp.department || '-',
      emp.employment_status || '-',
      emp.joining_date || '-',
      emp.payment_mode || '-',
      emp.pf_applicable || '-',
      emp.esi_applicable || '-',
      emp.current_salary || 0,
      payroll.deduction_type || '-',
      payroll.deduction_amount || 0,
      payroll.addition_type || '-',
      payroll.addition_amount || 0,
      payroll.incentive_type || '-',
      payroll.incentive_amount || 0,
      payroll.pf_amount || 0,
      payroll.esi_amount || 0,
      payroll.net_pay || 0,
      payroll.hr_remark || '-',
      payroll.salary_processing_required || '-',
      payroll.payment_status || 'Not Paid',
      payroll.remarks || '-',
      emp.bank_name || '-',
      emp.bank_account_number || '-',
      emp.bank_ifsc_code || '-',
    ]
  })

  // Combine all data
  const wsData = [...headerRows, tableHeaders, ...tableData]

  // Create worksheet
  const ws = XLSX.utils.aoa_to_sheet(wsData)

  // Set column widths for full-width display
  const colWidths = [
    { wch: 14 }, // Employee ID
    { wch: 25 }, // Employee Name
    { wch: 20 }, // Designation
    { wch: 20 }, // Department
    { wch: 18 }, // Employment Status
    { wch: 14 }, // Joining Date
    { wch: 14 }, // Payment Mode
    { wch: 14 }, // PF Applicable
    { wch: 14 }, // ESI Applicable
    { wch: 15 }, // Current Salary
    { wch: 18 }, // Deduction Type
    { wch: 16 }, // Deduction Amount
    { wch: 18 }, // Addition Type
    { wch: 16 }, // Addition Amount
    { wch: 18 }, // Incentive Type
    { wch: 16 }, // Incentive Amount
    { wch: 14 }, // PF Amount
    { wch: 14 }, // ESI Amount
    { wch: 15 }, // Net Pay
    { wch: 25 }, // HR Remark
    { wch: 22 }, // Salary Processing Required
    { wch: 15 }, // Payment Status
    { wch: 30 }, // Remarks
    { wch: 25 }, // Bank Name
    { wch: 20 }, // Account Number
    { wch: 15 }, // IFSC Code
  ]
  ws['!cols'] = colWidths

  // Add worksheet to workbook
  XLSX.utils.book_append_sheet(wb, ws, `Payroll ${getMonthName(month)}`)

  // Generate Excel file as blob
  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' })
  return new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
}

/**
 * Generate a comprehensive PDF report with landscape orientation for full-width
 */
export function generatePDFReport(data: ReportData): Blob {
  const { month, year, employees, totalGrossSalary, totalDeductions, totalAdditions, totalNetSalary, generatedBy } = data

  // Create PDF in landscape mode for full width
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a3', // A3 for more width
  })

  // Header
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('PAYROLL REPORT', doc.internal.pageSize.getWidth() / 2, 15, { align: 'center' })
  
  doc.setFontSize(14)
  doc.text(`${getMonthName(month)} ${year}`, doc.internal.pageSize.getWidth() / 2, 23, { align: 'center' })

  // Summary section
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  let yPos = 35
  doc.text(`Generated On: ${new Date().toLocaleString()}`, 15, yPos)
  yPos += 6
  doc.text(`Generated By: ${generatedBy}`, 15, yPos)
  yPos += 10

  doc.setFont('helvetica', 'bold')
  doc.text('Summary:', 15, yPos)
  yPos += 6
  doc.setFont('helvetica', 'normal')
  doc.text(`Total Employees: ${employees.length}`, 15, yPos)
  yPos += 6
  doc.text(`Total Gross Salary: ${formatCurrency(totalGrossSalary)}`, 15, yPos)
  yPos += 6
  doc.text(`Total Deductions: ${formatCurrency(totalDeductions)}`, 15, yPos)
  yPos += 6
  doc.text(`Total Additions: ${formatCurrency(totalAdditions)}`, 15, yPos)
  yPos += 6
  doc.text(`Total Net Salary: ${formatCurrency(totalNetSalary)}`, 15, yPos)
  yPos += 10

  // Prepare table data - only actual fields from database
  const tableHeaders = [
    'Emp ID',
    'Name',
    'Designation',
    'Dept',
    'Payment\nMode',
    'Current\nSalary',
    'Deduction\nType',
    'Deduction\nAmount',
    'Addition\nType',
    'Addition\nAmount',
    'Incentive\nType',
    'Incentive\nAmount',
    'PF\nAmount',
    'ESI\nAmount',
    'Net Pay',
    'HR\nRemark',
    'Payment\nStatus',
    'Bank',
    'Account',
  ]

  const tableData = employees.map((emp) => {
    const payroll = emp.payroll as any || {}
    return [
      emp.employee_id,
      emp.employee_name,
      emp.designation || '-',
      emp.department || '-',
      emp.payment_mode || '-',
      formatCurrency(emp.current_salary || 0),
      payroll.deduction_type || '-',
      formatCurrency(payroll.deduction_amount || 0),
      payroll.addition_type || '-',
      formatCurrency(payroll.addition_amount || 0),
      payroll.incentive_type || '-',
      formatCurrency(payroll.incentive_amount || 0),
      formatCurrency(payroll.pf_amount || 0),
      formatCurrency(payroll.esi_amount || 0),
      formatCurrency(payroll.net_pay || 0),
      payroll.hr_remark || '-',
      payroll.payment_status || 'Not Paid',
      emp.bank_name || '-',
      emp.bank_account_number || '-',
    ]
  })

  // Generate table with auto-width
  autoTable(doc, {
    startY: yPos,
    head: [tableHeaders],
    body: tableData,
    styles: {
      fontSize: 7,
      cellPadding: 2,
      overflow: 'linebreak',
      halign: 'left',
    },
    headStyles: {
      fillColor: [59, 130, 246],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'center',
    },
    columnStyles: {
      0: { cellWidth: 15 }, // Emp ID
      1: { cellWidth: 25 }, // Name
      2: { cellWidth: 18 }, // Designation
      3: { cellWidth: 16 }, // Dept
      4: { cellWidth: 16 }, // Payment Mode
      5: { cellWidth: 18, halign: 'right' }, // Current Salary
      6: { cellWidth: 18 }, // Deduction Type
      7: { cellWidth: 16, halign: 'right' }, // Deduction Amount
      8: { cellWidth: 18 }, // Addition Type
      9: { cellWidth: 16, halign: 'right' }, // Addition Amount
      10: { cellWidth: 18 }, // Incentive Type
      11: { cellWidth: 16, halign: 'right' }, // Incentive Amount
      12: { cellWidth: 14, halign: 'right' }, // PF Amount
      13: { cellWidth: 14, halign: 'right' }, // ESI Amount
      14: { cellWidth: 18, halign: 'right' }, // Net Pay
      15: { cellWidth: 20 }, // HR Remark
      16: { cellWidth: 16 }, // Payment Status
      17: { cellWidth: 18 }, // Bank
      18: { cellWidth: 18 }, // Account
    },
    theme: 'grid',
    tableWidth: 'auto',
  })

  // Return as blob
  return doc.output('blob')
}

/**
 * Download a blob as a file
 */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
